version: '3.9'
services:
  database:
    container_name: database
    image: mariadb:10.6.3
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: dbpassword
      MARIADB_USER: root
      MARIADB_DATABASE: db_appointment
      MARIADB_HOST: database
    volumes:
      - ./scripts/migrations.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - application
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      MARIADB_ROOT_PASSWORD: dbpassword
      MARIADB_USER: root
      MARIADB_DATABASE: db_appointment
      MARIADB_HOST: database
    networks:
      - application
    depends_on:
      - database
networks:
  application:
