version: "3.9"
services:
  database:
    image: mariadb:10.6.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: dbpassword
      MARIADB_DATABASE: db_appointment
    volumes:
      - ./scripts/migrations.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - application
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: dbpassword
      MARIADB_DATABASE: db_appointment
    ports:
      - "8080:8080"
    networks:
      - application
    depends_on:
      - database
networks:
  application:
